---
# tasks file for install_postgres
#

- name: install postgresql-server 14
  apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: true

- name: enable and start service
  service:
    name: postgresql
    state: started
    enabled: true

