---

- hosts: all
  become: yes
  name: otus lesson 33 OSPF
  vars_files:
    - defaults/main.yaml

  tasks:
    - name: install base tools
      ansible.builtin.apt:
        name:
          - vim
          - traceroute
          - tcpdump
          - net-tools
        state: present
        update_cache: true

    - name: disable ufw service
      ansible.builtin.service:
        name: ufw
        state: stopped
        enabled: false

    - name: add gpg frrouting.org
      ansible.builtin.apt_key:
        url: "https://deb.frrouting.org/frr/keys.asc"
        state: present

    - name: add frr repo
      ansible.builtin.apt_repository:
        repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
        state: present

    - name: install FRR packages
      ansible.builtin.apt:
        name:
          - frr
          - frr-pythontools
        state: present
        update_cache: true

    - name: set up forward packages across routers
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    - name: set up asynchronous routing
      ansible.builtin.sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        state: present

    - name: base set up OSPF
      ansible.builtin.template:
        src: template/daemons
        dest: /etc/frr/daemons
        owner: frr
        group: frr
        mode: 0640

    - name: set up OSPF
      ansible.builtin.template:
        src: template/frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640
      tags:
      - setup_ospf

    - name: restart FRR
      ansible.builtin.service:
        name: frr
        state: restarted
        enabled: true
      tags:
      - setup_ospf


